specVersion: 1.0.0
name: heiko-liquid-staking-subql
version: 1.0.0
description: >-
  Subql service for Liquid-staking in the heiko network
repository: 'https://github.com/parallel-finance/liquid-staking-subql'
runner:
  node:
    name: '@subql/node'
    version: 'v1.0.0'
  query:
    name: '@subql/query'
    version: 'v1.0.0'
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://regnet4-rpc.parallel.fi'
  chainId: '0xaef53b373e23b1e01b7335dc6e9ae9618c07fd04c268d9a9149ae7c46032f9ee'
  dictionary: ''
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler

        - handler: handleStakeEvent
          kind: substrate/EventHandler
          filter:
            module: liquidStaking
            method: Staked

        - handler: handleUnstakeEvent
          kind: substrate/EventHandler
          filter:
            module: liquidStaking
            method: Unstaked

        - handler: handleUpdateLedger
          kind: substrate/EventHandler
          filter:
            module: liquidStaking
            method: StakingLedgerUpdated

        - handler: handleSTokenIssued
          kind: substrate/EventHandler
          filter:
            module: assets
            method: Issued

        - handler: handleSTokenBurned
          kind: substrate/EventHandler
          filter:
            module: assets
            method: Burned

        - handler: handleSTokenTransferred
          kind: substrate/EventHandler
          filter:
            module: assets
            method: Transferred

        - handler: handleSTokenTraded
          kind: substrate/EventHandler
          filter:
            module: amm
            method: Traded

        - handler: handleLiquidityAdded
          kind: substrate/EventHandler
          filter:
            module: amm
            method: LiquidityAdded

        - handler: handleLiquidityRemoved
          kind: substrate/EventHandler
          filter:
            module: amm
            method: LiquidityRemoved

        - handler: handleSTokenDeposited
          kind: substrate/EventHandler
          filter:
            module: loans
            method: Deposited

        - handler: handleSTokenRedeemed
          kind: substrate/EventHandler
          filter:
            module: loans
            method: Redeemed

        - handler: handleSTokenBorrowed
          kind: substrate/EventHandler
          filter:
            module: loans
            method: Borrowed

        - handler: handleSTokenRepaid
          kind: substrate/EventHandler
          filter:
            module: loans
            method: RepaidBorrow

        - handler: handleSTokenLiquidatedBorrow
          kind: substrate/EventHandler
          filter:
            module: loans
            method: LiquidatedBorrow

        - handler: handleSupplierRewardDistributed
          kind: substrate/EventHandler
          filter:
            module: loans
            method: DistributedSupplierReward

        - handler: handleRewardPaid
          kind: substrate/EventHandler
          filter:
            module: loans
            method: RewardPaid

        - handler: handleFarmingRewardPaid
          kind: substrate/EventHandler
          filter:
            module: farming
            method: RewardPaid

        - handler: handleFarmingDeposited
          kind: substrate/EventHandler
          filter:
            module: farming
            method: AssetsDeposited

        - handler: handleFarmingWithdrew
          kind: substrate/EventHandler
          filter:
            module: farming
            method: AssetsWithdrew
