name: Deploy

on:
  workflow_dispatch:

jobs:
  publish:
    name: IPFS publish
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        manifest: ['heiko', 'parallel', 'project']

    steps:
      - uses: actions/checkout@v2

      - name: Use node version 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Generate schema type
        run: yarn codegen

      - name: Publish to IPFS
        run: yarn ipfs:publish -f ${{ matrix.manifest }}.yaml
        env:
          SUBQL_ACCESS_TOKEN: ${{ secrets.SUBQL_ACCESS_TOKEN }}
